# .github/workflows/compute-python-package-version.yml
on:
  workflow_call:
    outputs:
      version:
        description: "Computed version"
        value: ${{ jobs.compute.outputs.version }}

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.compute.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure tags are up to date
        run: |
          git fetch --force --tags --prune --recurse-submodules=no

      - name: Run version calculation script
        id: compute
        uses: cpprentice/ci-templates/.github/actions/call-python-package-version-script@main

      - name: Print extracted version from shared job
        run: echo "${{ steps.compute.outputs.version }}"